### ISSUE TITLE
Can this work with dynamic pages?

### ISSUE THREAD

**Issue by djudju2012** [ajoslin/angular-mobile-nav#24]
Nice work!
I am wondering how this can be used with dynamic (opposed to static) pages.
In my angularjs project I use 

`<a href="" ng-click="open(note.id)"> with id being provided by angularjs`
OR
`<a href="#/notes/{{note.id}}">{{note.title}}</a>`

I tried to translate this with the ng-lap directive but I can't get it to work
i.e. `<a ng-tap="$navigate.go('#/notes/{{note.id}}')">` does not work.

Any clue.

Thank you

**Comment by ajoslin** [comment]
Try removing the '#' from the path.

You aren't updating the browser's location, instead angular's record of it, which doesn't include the '#'.

Also, you're already in an angular expression in this case so you're concatenating to a string instead of using `{{}}` for your path.

Here's what you need:

``` html
<a ng-tap="$navigate.go('/notes/' + note.id)">
```

This is the same as it would be in a normal javascript expression:

``` js
$navigate.go('/notes/' + note.id);
```

I would also recommend making a function of some sort called `goToNote(noteId)` on your controller for this.
