### ISSUE TITLE
Moving from Makefile to Grunt

### ISSUE THREAD

**Issue by 0x-r4bbit** [ajoslin/angular-mobile-nav#32]
Yo Andy,

what to you think?
Also, [this flow](https://github.com/ajoslin/angular-mobile-nav/issues/30#issuecomment-15661399) could be automated then and it makes contributing much easier. :)

**Comment by ajoslin** [comment]
This project will actually be moving to ui-router soon.

All I need to do is integrate back button history support to there.  
Then once they add ng-animate this project will be sort of useless and 
trumped by a better implementation (with states, nested views, and real 
back button support instead of my fake $navigate.back()).

All you'll see left of angular-mobile-nav is probably some sort of 
"fancy-mobile-animations.css" addon for ui-router.

Nevertheless, moving to a Gruntfile would be easy.  I just kind of don't 
want to spend time on this library anymore - I'd rather spend time 
getting back button direction-detection working on ui-router when I have 
a spare day :-)

**Comment by 0x-r4bbit** [comment]
Fair enough!
