### ISSUE TITLE
Add back button support for browsers

### ISSUE THREAD

**Issue by ajoslin** [ajoslin/angular-mobile-nav#4]
Make it so the browser back button goes back as intended, using `window.onpopstate`.

**Comment by petebacondarwin** [comment]
More over can't you trigger all navigation off $location changes allowing people to just use hrefs rather than the navigation services?

**Comment by ajoslin** [comment]
I can't know when a back is done properly with just hrefs.  The timing of `window.onpopstate` is weird; I'm still not sure if I'll even be able to use it with the new nav service.

Remember a couple months ago when I tried this with only a custom ng-view element?  It had lots of troubles with back.  and I didn't have a way for the developer to define the transition to use.

**Comment by petebacondarwin** [comment]
Set transitions on the route?

... sent from my tablet

**Comment by ajoslin** [comment]
Yeah, but then people couldn't define custom transitions. Which isn't the end of the world I guess.  I'm still not sure if I'd be able to get back working.

**Comment by petebacondarwin** [comment]
Can't you define custom transitions as angular services or by registering
them with a transition service and reference them by name in the route?

Pete
...from my mobile.

**Comment by ajoslin** [comment]
Sorry, I meant a custom transition for a route depending on the situation as easily as it is now.

**Comment by petebacondarwin** [comment]
How about a directive on anchors called transition which could take an
{{interpolated value}}?

Pete
...from my mobile.

**Comment by ajoslin** [comment]
That's true, I could do that.  But I don't like checking window.onpopstate, it's messy.

**Comment by smathson** [comment]
Hey @ajoslin, just wondering what your latest thoughts on this were.

I'd love to be able to use this (and hopefully contribute back) with our mobile app because it has a lot of overlap with our current solution, but I'm running into this issue. For our mobile apps we're going with a hybrid approach where most of our fixed navigation elements are native components, so the "back" action is just a history.back() on the webView. I could pretty easily change that to a custom event and have that trigger a $navigate.back() instead, but if you're planning on making mobile-nav more route history aware anyway, I'd rather help with that in some way.

**Comment by ajoslin** [comment]
Hi Scott! Thanks for stopping by. 

It's in the idea list, but I dunno if I'll get to it soon. School just started so I have less time, and there are other bugs. 

My personal use for this doesn't require regular browser support, but if enough people want it I will make it sooner than later.

**Comment by mattrjensen** [comment]
FYI, I believe this issue also applies to the 'Back' button on Android phones too (it seems to on mine anyway).
