### ISSUE TITLE
New scope after going back

### ISSUE THREAD

**Issue by bugwelle** [ajoslin/angular-mobile-nav#47]
So, hello :)
Maybe someone can help me. I have a form in which are inputs and a link to another page where I can select an item. After I selected an item, I go back to the form page.
The problem is: I have no idea how I submit the selected item to the form page and also the user data in the inputs is lost. It seems that another scope is created instead of using the old one.
I could use $rootScope to submit the selcted item, but that's not what I want :)
Here's an image of how it should be:
![angular-nav](https://f.cloud.github.com/assets/1667306/459206/2e3250de-b3fb-11e2-8046-df731ba1a738.png)

Greetings from Germany,
archer96 (Andre)

**Comment by fotomut** [comment]
Perhaps you could create a service that manages persisting certain scope
elements.

There are other ways to do this also, i am sure.

**Comment by ajoslin** [comment]
Hi archer,

Yeah, you could use a service to store data that's shared between pages - or put that info into the URL.

**Comment by bugwelle** [comment]
Thanks for answering :)
Storing data by using a serice isn't a bad idea. I thought about that, too. :D
But shouldn't the old scope be used instead of creating a new one when going back?

**Comment by fotomut** [comment]
Scopes are not reused in the way you are describing. Every time a
controller is invoked it has to set up the scope it needs from scratch.

This is actually a useful architecture because if scopes were reused it
would get very messy. Much simpler for the programmer to manually ensure
the scope is good upon initialization of a controller rather than making
sure to clean up a scope upon destruction.

**Comment by bugwelle** [comment]
Ok, thanks :)
I didn't knew that (still learning AngularJS).
I'll create a service to store the data temporarily.

Thanks and have a nice day :D
