### ISSUE TITLE
use $transition from angularjs bootstrap

### ISSUE THREAD

**Issue by petebacondarwin** [ajoslin/angular-mobile-nav#7]
https://github.com/angular-ui/bootstrap/blob/master/src/transition/transition.js

**Comment by ajoslin** [comment]
Earlier, I couldn't use $transition because I was doing lots of weird class stuff.  But now there's just one set of trigger classes and webkit-keyframes to trigger.

The only thing is that now I catch the `webkitAnimationEnd` event instead of `webkitTransitionEnd`. We should add an `options` parameter for `$transition` on the bootstrap repo, and give an option for binding to the `xxAnimationEnd` events instead. I'll open a PR.

**Comment by ajoslin** [comment]
I decided this wasn't worth it.  I tried to do it with $transition support for animationEnd added, and it's too many cases to account for.  I still want $change to work for any two pages (so people can transition one onto another without using the view system).
